import {
  IconBrandReact,
  IconBrandTypescript,
  IconBrandTailwind,
  IconBrandPython,
  IconBrandDocker,
  IconBrandGithub,
  IconBrandDjango,
  IconStack,
  IconApi,
  IconTestPipe,
  IconBrandVercel,
  IconDatabase,
  IconFileCode,
  IconTrain,
} from "@tabler/icons-react";

export const TECHSTACK_INFO = [
  { name: "React", icon: IconBrandReact },
  { name: "TypeScript", icon: IconBrandTypescript },
  { name: "Tailwind CSS", icon: IconBrandTailwind },
  { name: "Framer Motion", icon: IconStack },
  { name: "Zustand", icon: IconStack },
  { name: "React Testing", icon: IconTestPipe },
  { name: "Python", icon: IconBrandPython },
  { name: "FastAPI", icon: IconApi },
  { name: "Django", icon: IconBrandDjango },
  { name: "REST API", icon: IconApi },
  { name: "PostgreSQL", icon: IconDatabase },
  { name: "Pytest", icon: IconTestPipe },
  { name: "Swagger", icon: IconFileCode },
  { name: "Docker", icon: IconBrandDocker },
  { name: "GitHub", icon: IconBrandGithub },
  { name: "CI/CD", icon: IconBrandGithub },
  { name: "Railway", icon: IconTrain },
  { name: "Vercel", icon: IconBrandVercel },
];
